language: c

python:
  - "2.7"

sudo: false

matrix:
  include:
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - export PATH=$PATH:$PWD/here/bin

install:
  - luarocks make rockspecs/tpdu-scm-0.rockspec

before_script:
  - luarocks install luacov-coveralls
  - luarocks install lunitx

script: 
  - cd test
  - lunit.sh test.lua

after_success:
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
